#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    foreground = '#fff'
    background = '#E36464'
    leading_diamond = ''
    trailing_diamond = ''
    template = '{{ .UserName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    foreground = '#fff'
    background = 'green'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'diamond'
    foreground = '#fff'
    background = 'lightCyan'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' git({{ .HEAD }}) '

    [blocks.segments.properties]
      branch_icon = ''

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    foreground = '#fff'
    background = 'lightMagenta'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04'
