#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#07585c'
    leading_diamond = ''
    template = ' {{ .UserName }}@{{ .HostName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#ffffff'
    background = '#3e9022'
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#ffffff'
    background = '#de076f'
    template = ' {{ .UpstreamIcon }}{{ .HEAD }} '

    [blocks.segments.properties]
      branch_icon = ''
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'spotify'
    style = 'plain'
    foreground = '#ffffff'
    background = '#491545'
    template = '  {{ .Icon }}{{ if ne .Status "stopped" }}{{ .Artist }} - {{ .Track }}{{ end }} '

    [blocks.segments.properties]
      paused_icon = ' '
      playing_icon = ' '
      stopped_icon = ' '
      track_separator = ' - '

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#491515'
    background_templates = ['{{ if gt .Code 0 }}#f1184c{{ end }}']
    trailing_diamond = ''
    template = '  '

    [blocks.segments.properties]
      always_enabled = true
