#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
console_title_template = '{{if .Root}}(Admin) {{end}}{{.Folder}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#242424'
    background = '#f1184c'
    template = ''

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#3A86FF'
    background = '#282c34'
    leading_diamond = ' '
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '

  [[blocks.segments]]
    type = 'time'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#FFBB00'
    background = '#242424'
    template = '{{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04:05'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#33DD2D'
    background = '#242424'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#3A86FF'
    background = '#242424'
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'dotnet'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#0184bc'
    template = '  {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#8800dd'
    template = ' <#fefefe></> {{ .FormattedMs }} '

    [blocks.segments.properties]
      style = 'austin'
      threshold = 1.0

  [[blocks.segments]]
    type = 'status'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#242424'
    background = '#33DD2D'
    background_templates = ['{{ if gt .Code 0 }}#f1184c{{ end }}']
    template = '  '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#f1184c'
    template = '➜ '
