#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#ffffff'
    template = '<#CB4B16>┏[</>{{ .UserName }}<#CB4B16>]</>'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#ffffff'
    template = '<#CB4B16>[</>{{ .HEAD }}<#CB4B16>]</>'

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#ffffff'
    template = '<#CB4B16>[</><#CB4B16>]</>'

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#ffffff'
    template = '<#CB4B16>[x</>{{ reason .Code }}<#CB4B16>]</>'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#ffffff'
    template = '<#CB4B16>┖[</>{{ .Path }}<#CB4B16>]></>'

    [blocks.segments.properties]
      style = 'full'
