#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#FFBD00'
    template = "{{ .UserName }}'s "

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#00C6F7'
    template = '{{ .Path }}/ '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#F62F2E'
    template = '<#ffffff>on</> {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '

    [blocks.segments.properties]
      fetch_status = true

  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    foreground = '#98C379'
    template = '<#ffffff>via</>  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '

    [blocks.segments.properties]
      fetch_version = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'diamond'
    foreground = '#85C980'
    trailing_diamond = ' '
    template = 'RAM:{{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB '

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#ffffff'
    leading_diamond = '┋'
    template = ' {{ .FormattedMs }} '

    [blocks.segments.properties]
      style = 'roundrock'
      threshold = 0.0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#FFBD00'
    template = '⮞ '
