#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{if .Root}}Admin: {{end}} {{.Folder}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffffff'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#0057b7'
    template = ''

  [[blocks.segments]]
    type = 'text'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#FBD951'
    background = '#0057b7'
    template = '  '

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    foreground = '#FBD951'
    background = '#0057b7'
    trailing_diamond = ''
    template = '{{ .Path }} '

    [blocks.segments.properties]
      home_icon = ''
      style = 'mixed'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffd700'
    background = '#0057b7'
    template = '   {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0}} {{ .StashCount }}{{ end }}{{ if gt .WorktreeCount 0}}  {{ .WorktreeCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#0057b7'
    background = '#3379c5'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#3379c5{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c57f33{{ end }}', '{{ if gt .Ahead 0 }}#79c533{{ end }}', '{{ if gt .Behind 0 }}#c53379{{ end }}']
    template = ''

    [blocks.segments.properties]
      fetch_stash_count = false
      fetch_status = false
      fetch_upstream_icon = false

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    leading_diamond = '<transparent,#49404f></>'
    trailing_diamond = ''

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = '#0057b7'
    foreground_templates = ['{{ if gt .Code 0 }}#a30000{{ end }}']
    background = '#ffd700'
    leading_diamond = '<transparent,#ffd700></>'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}  {{ else }} ♥ {{ end }}'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'text'
    style = 'diamond'
    foreground = '#FBD951'
    background = '#0057b7'
    leading_diamond = ''
    template = '  <#111111></>'

  [[blocks.segments]]
    type = 'battery'
    style = 'diamond'
    invert_powerline = true
    foreground = '#FBD951'
    background = '#0057b7'
    leading_diamond = ''
    template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}% <#111111></>'

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = ' '
      discharging_icon = ' '

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    invert_powerline = true
    foreground = '#FBD951'
    background = '#0057b7'
    leading_diamond = ''
    template = '  {{ .FormattedMs }} <#111111></>'

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    invert_powerline = true
    foreground = '#FBD951'
    background = '#0057b7'
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{ .CurrentDate | date .Format }}'

    [blocks.segments.properties]
      time_format = '_2,15:04'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#0057b7'
    template = ''

  [[blocks.segments]]
    type = 'os'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffd700'
    background = '#0057b7'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#FBD951'
    background = '#0057b7'
    template = ' '

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#0057b7'
    background = '#FBD951'
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '

    [blocks.segments.properties]
      display_host = false

[[blocks]]
  type = 'rprompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#0057b7'
    template = ''

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#FBD951'
    template = ''

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#0057b7'
    template = ''

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#FBD951'
    template = '  Ukraine'
