#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
console_title_template = '{{if .Root}} ⚡ {{end}}{{.Folder | replace "~" "🏚" }} @ {{.HostName}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#40189c'
    leading_diamond = ''
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#40189c'
    trailing_diamond = ''
    template = '| {{ .UserName }}@{{ .HostName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#01579B'
    leading_diamond = '<transparent,#01579B></>'
    trailing_diamond = ''
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      folder_icon = '...'
      folder_separator_icon = '<transparent>  </>'
      home_icon = ''
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#000000'
    background = '#00C853'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FF{{ end }}']
    template = ' {{ .HEAD }}{{ if .Staging.Changed }}<#FF6F00>  {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true

  [[blocks.segments]]
    type = 'dotnet'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#000000'
    background = '#00ffff'
    template = '  {{ .Full }} '

  [[blocks.segments]]
    type = 'angular'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#000000'
    template = '  {{ if .Error }}<#FE4A49>?</>{{ else }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'node'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#45bf17'
    background = '#000000'
    template = '  {{ .Full }} '

  [[blocks.segments]]
    type = 'npm'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#FE4A49'
    background = '#000000'
    template = ' {{ .Full }} '

  [[blocks.segments]]
    type = 'status'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#910000'
    template = '<transparent> </> {{ reason .Code }} '

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#29315A'
    leading_diamond = ''
    template = ' {{ .FormattedMs }}s '

    [blocks.segments.properties]
      style = 'dallas'
      threshold = 0.0

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#3EC669'
    background = '#29315A'
    template = '<transparent>  </>{{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04:05 | Monday'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#ffffff'
    foreground_templates = ['{{ if gt .Code 0 }}#ff0000{{ end }}']
    template = '❯ '

    [blocks.segments.properties]
      always_enabled = true
