#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#3A86FF'
    leading_diamond = ''
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    foreground = '#ffffff'
    background = '#3A86FF'
    template = ' {{ .UserName }}@{{ .HostName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#ff479c'
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'time'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#193549'
    background = '#4caf50'
    template = ' {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '2006-01-02 15:04:05'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#193549'
    background = '#fffb38'
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'node'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#6CA35E'
    template = '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#193549'
    background = '#ffff66'
    template = '  '

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#2e9599'
    background_templates = ['{{ if gt .Code 0 }}#f1184c{{ end }}']
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = '  '

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#f1184c'
    template = ' '
