#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
console_title_template = '{{if .Root}} ⚡ {{end}}{{.Folder | replace "~" "🏚" }} @ {{.HostName}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#dd1e1e'
    background = '#000000'
    template = ' ⚡ '

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = '#ffffff'
    background = 'transparent'
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#43CCEA'
    background = '#5a3d29'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      folder_icon = '...'
      folder_separator_icon = '<transparent>  </>'
      home_icon = ''
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'diamond'
    foreground = '#000000'
    background = '#00C853'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}', '{{ if gt .Ahead 0 }}#B388FF{{ end }}', '{{ if gt .Behind 0 }}#B388FF{{ end }}']
    leading_diamond = '<parentBackground,background></>'
    template = ' {{ .HEAD }}{{ if .Staging.Changed }}<#FF6F00>  {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#5a3d29'
    background = '#2ba1bb'
    leading_diamond = '<parentBackground,background></>'
    template = ' {{ .FormattedMs }}s '

    [blocks.segments.properties]
      style = 'dallas'
      threshold = 0.0

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#910000'
    template = '{{ if gt .Code 0 }}<parentBackground,background></><transparent> </> {{ reason .Code }} <background,transparent></>{{ else }}<parentBackground,transparent></>{{ end }}'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    foreground = '#43CCEA'
    background = '#5a3d29'
    leading_diamond = ''
    template = '  {{ if .SSHSession }} {{ end }}{{ .UserName }}<transparent> / </>{{ .HostName }}'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#43CCEA'
    background = '#5a3d29'
    template = '<transparent>  </>{{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '3:04:05 PM'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#ffffff'
    foreground_templates = ['{{ if gt .Code 0 }}#ff0000{{ end }}']
    template = '❯ '

    [blocks.segments.properties]
      always_enabled = true
