#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#7E46B6'
    template = '{{ .UserName }} '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffffff'
    template = 'in '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#87FF00'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#5FD7FF'
    template = '<#ffffff>on</> {{ .HEAD }}{{ if .Staging.Changed }}<#87FF00> ● {{ .Staging.String }}</>{{ end }}{{ if .Working.Changed }}<#D75F00> ● {{ .Working.String }}</>{{ end }} '

    [blocks.segments.properties]
      branch_ahead_icon = ''
      branch_behind_icon = ''
      branch_gone_icon = ''
      branch_icon = ''
      branch_identical_icon = ''
      cherry_pick_icon = ''
      commit_icon = ''
      fetch_status = true
      merge_icon = ''
      rebase_icon = ''
      revert_icon = ''
      tag_icon = ''

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#D75F00'
    template = 'λ '
