#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#FFFFFF'
    template = '<#0377C8># </><#0377C8>{{ .UserName }}</> <#ffffff>in</> <#4A9207>{{ .HostName }}</> '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#0973C0'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      folder_icon = ''
      folder_separator_icon = '  '
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#B8B80A'
    template = '<#ffffff>on git:</>{{ .HEAD }} '

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#ffffff'
    template = '[{{ .CurrentDate | date .Format }}]'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#CECE04'
    template = ' '

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = '#100e23'
    template = ' {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} '

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#CB4B16'
    template = ' {{ reason .Code }} '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#CC4B16'
    template = '➜ '
