#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{.Folder}}{{if .Root}} :: root{{end}} :: {{.Shell}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = 'yellow'
    template = '  '

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    foreground = 'black'
    background = 'lightBlue'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'mixed'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'black'
    background = 'green'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}']
    template = ' {{ .HEAD }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }} '

    [blocks.segments.properties]
      branch_ahead_icon = '↑'
      branch_behind_icon = '↓'
      branch_gone = '≢'
      branch_icon = ' '
      branch_identical_icon = '≡'
      cherry_pick_icon = '✓ '
      commit_icon = '▷ '
      fetch_status = true
      merge_icon = '◴ '
      no_commits_icon = '[no commits]'
      rebase_icon = 'Ɫ '
      tag_icon = '▶ '
