#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#c44569'
    leading_diamond = ''
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}}'

    [blocks.segments.properties]
      windows = ''

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#c44569'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'node'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#f78fb3'
    template = '  {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }} '

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#f78fb3'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} '

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#caffbf'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#FCA17D{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#f17c37{{ end }}']
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }} '

    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#ffffff'
    background = '#83769c'
    template = ' {{ .FormattedMs }} '

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#FFD700'
    background = '#86BBD8'
    template = ' ⚡'

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#ffffff'
    background = '#86BBD8'
    template = ' {{ .UserName }} '

  [[blocks.segments]]
    type = 'shell'
    style = 'diamond'
    invert_powerline = true
    foreground = '#ffffff'
    background = '#33658A'
    trailing_diamond = ''
    template = ' {{ .Name }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    template = '  '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffffff'
    template = '<#69FF94>❯</>'
