#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#FFE082'
    template = '@{{ .UserName }} ➜'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#56B6C2'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'go'
    style = 'powerline'
    foreground = '#7FD5EA'
    template = '({{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}) '

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    foreground = '#9e7eff'
    template = '( {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}) '

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#56B6C2'
    template = '<#E8CC97>git(</>{{ .HEAD }}<#E8CC97>) </>'

    [blocks.segments.properties]
      branch_icon = ''

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    foreground = '#FFAB91'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      always_enabled = false
      style = 'austin'
      threshold = 100.0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'battery'
    style = 'powerline'
    foreground = '#193549'
    foreground_templates = ['{{if eq "Charging" .State.String}}#64B5F6{{end}}', '{{if eq "Discharging" .State.String}}#E36464{{end}}', '{{if eq "Full" .State.String}}#66BB6A{{end}}']
    template = '[{{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}]'

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = ' '
      discharging_icon = ' '
