#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'diamond'
    foreground = '#ff8800'
    template = '{{ round .PhysicalPercentUsed .Precision }}% '

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'diamond'
    foreground = '#ff8800'
    template = '{{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB '

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = '#ff8800'
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '

    [blocks.segments.properties]
      macos = 'mac'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ff8800'
    template = '$'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#ff8800'
    template = '{{ .UserName }}:'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#62c0ff'

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#62c0ff'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#6287ff{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#7f62ff{{ end }}', '{{ if gt .Ahead 0 }}#9962ff{{ end }}', '{{ if gt .Behind 0 }}#c062ff{{ end }}']
    template = '<#ff8800>on</> {{.UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_max_length = 25.0
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ff8800'
    template = '❯ '
