#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#fff'
    background = '#003543'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}}'

    [blocks.segments.properties]
      windows = ''

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#d2ff5e'
    background = '#003543'
    template = '{{ .UserName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#003544'
    background = '#0087D8'
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#193549'
    background = '#d2ff5e'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#f17c37{{ end }}']
    template = ' {{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true

  [[blocks.segments]]
    type = 'status'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#242424'
    background = '#33DD2D'
    background_templates = ['{{ if gt .Code 0 }}#f1184c{{ end }}']
    template = '  '

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'battery'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#242424'
    background = '#f36943'
    background_templates = ['{{if eq "Charging" .State.String}}#33DD2D{{end}}', '{{if eq "Discharging" .State.String}}#FFCD58{{end}}', '{{if eq "Full" .State.String}}#0476d0{{end}}']
    template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}  '

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#003544'
    background = '#0087D8'
    template = '  {{ .Venv }} '

    [blocks.segments.properties]
      display_mode = 'context'
      fetch_virtual_env = true

  [[blocks.segments]]
    type = 'time'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#fff'
    background = '#003543'
    template = '<#fff>  </>{{ .CurrentDate | date .Format }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#FFD700'
    template = ' ⚡ '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#f1184c'
    template = '🚀 '

[transient_prompt]
  foreground = '#FFD700'
  background = 'transparent'
  template = '{{if .Root}}⚡ {{end}}🚀 '
