#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    foreground = '#F1FA8C'
    template = '<#42E66C> </><b>{{ .Path }}</b>'

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'diamond'
    foreground = '#43CCEA'
    template = '<#ffffff> ⚡ </><b>{{ .HEAD }}</b>'

    [blocks.segments.properties]
      branch_icon = ''

  [[blocks.segments]]
    type = 'text'
    style = 'diamond'
    foreground = '#ff0000'
    template = '<#ff0000> ◉</>'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#FFFFFF'
    template = '>'
