#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#EB9654'
    leading_diamond = ''
    template = '{{ if .SSHSession }} {{ end }}{{ .UserName }} '

    [blocks.segments.properties]
      display_host = false

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#3f3f3f'
    background = 'lightYellow'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#ffffff'
    background = '#25AFF3'
    template = ' branch ({{ .HEAD }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}) '

    [blocks.segments.properties]
      fetch_status = true

  [[blocks.segments]]
    type = 'spotify'
    style = 'plain'
    foreground = '#ffffff'
    background = '#1BD760'
    template = ' {{ .Icon }}{{ if ne .Status "stopped" }}{{ .Artist }} - {{ .Track }}{{ end }} '

    [blocks.segments.properties]
      paused_icon = ''
      playing_icon = ''
      stopped_icon = ''
      track_separator = ' - '

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#ffffff'
    background = '#cc00ff'
    template = ' {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04:05'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#ffffff'
    background = '#49404f'
    template = ' {{ .FormattedMs }}s '

    [blocks.segments.properties]
      style = 'dallas'
      threshold = 0.0

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#00897b'
    background_templates = ['{{ if .Error }}#e91e63{{ end }}']
    trailing_diamond = ''

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#ffffff'
    foreground_templates = ['{{ if gt .Code 0 }}#ff0000{{ end }}']
    template = '❯ '

    [blocks.segments.properties]
      always_enabled = true
