#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'lightBlue'
    foreground_templates = ['{{ if .Root }}lightRed{{ end }}']
    template = '<{{ if .Root }}lightBlue{{ else }}green{{ end }}>┌──(</>{{ .UserName }}{{ if .Root }}💀{{ else }}㉿{{ end }}{{ .HostName }}<{{ if .Root }}lightBlue{{ else }}green{{ end }}>)</>'

    [blocks.segments.properties]
      display_host = true

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'yellow'
    template = '<{{ if .Root }}lightBlue{{ else }}green{{ end }}>-[</> {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }}{{ end }}{{ .Full }}{{ end }}<{{ if .Root }}lightBlue{{ else }}green{{ end }}>]</>'

    [blocks.segments.properties]
      fetch_version = false
      fetch_virtual_env = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'lightWhite'
    template = '<{{ if .Root }}lightBlue{{ else }}green{{ end }}>-[</>{{ .Path }}<{{ if .Root }}lightBlue{{ else }}green{{ end }}>]</>'

    [blocks.segments.properties]
      folder_separator_icon = '<#c0c0c0>/</>'
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'white'
    template = '<{{ if .Root }}lightBlue{{ else }}green{{ end }}>-[</>{{ .HEAD }}<{{ if .Root }}lightBlue{{ else }}green{{ end }}>]</>'

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'white'
    template = ' {{ .FormattedMs }} '

    [blocks.segments.properties]
      always_enabled = true
      style = 'round'

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = 'green'
    foreground_templates = ['{{ if gt .Code 0 }}red{{ end }}']
    template = ' {{ if gt .Code 0 }}{{else}}{{ end }} '

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'lightBlue'
    template = '<{{ if .Root }}lightBlue{{ else }}green{{ end }}>└─</>{{ if .Root }}<lightRed>#</>{{ else }}${{ end }} '
