#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
console_title_template = '{{ if .Root }}root @ {{ end }}{{ .Shell }} in {{ .Folder }}'
osc99 = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#D6DEEB'
    background = '#575656'
    leading_diamond = ''
    template = ' {{ if .WSL }} on {{ end }}{{ .Icon }} '

    [blocks.segments.properties]
      alpine = ''
      arch = ''
      centos = ''
      debian = ''
      elementary = ''
      fedora = ''
      gentoo = ''
      linux = ''
      macos = ''
      manjaro = ''
      mint = ''
      opensuse = ''
      raspbian = ''
      ubuntu = ''
      windows = ''

  [[blocks.segments]]
    type = 'shell'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#011627'
    background = '#00C7FC'
    template = '  {{ .Name }} '

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#D6DEEB'
    background = '#EF541C'
    template = '  admin '

  [[blocks.segments]]
    type = 'cmake'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#E8EAEE'
    background = '#1E9748'
    template = '   cmake {{ .Full }} '

  [[blocks.segments]]
    type = 'python'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#011627'
    background = '#FFDE57'
    template = '  {{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }} '

    [blocks.segments.properties]
      display_mode = 'context'

  [[blocks.segments]]
    type = 'go'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#7FD5EA'
    template = ' ‭ {{ .Full }} '

  [[blocks.segments]]
    type = 'rust'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#193549'
    background = '#99908A'
    template = '  {{ .Full }} '

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#011627'
    background = '#1BD4CD'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#16B1AC{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#16B1AC{{ end }}', '{{ if gt .Ahead 0 }}#B787D7{{ end }}', '{{ if gt .Behind 0 }}#B787D7{{ end }}']
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#CAEBE1>  {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = '#414141'
    foreground_templates = ['{{ if gt .Code 0 }}#D6DEEB{{ end }}']
    background = '#03DED3'
    background_templates = ['{{ if gt .Code 0 }}#E44141{{ end }}']
    leading_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#D6DEEB'
    background = '#575656'
    trailing_diamond = ''
    template = '  {{ .FormattedMs }} '

    [blocks.segments.properties]
      style = 'roundrock'
      threshold = 0.0

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#D6DEEB'
    template = '╭─'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#F2D3B6'
    template = '{{ .CurrentDate | date .Format }} <#79DFE1>|</>'

    [blocks.segments.properties]
      time_format = '<#D6DEEB> 15:04:05</> <#79DFE1>|</>  2 Jan, Monday'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    foreground = '#B6D6F2'
    leading_diamond = '<#00C7FC>  </><#B6D6F2> in </>'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      folder_icon = '  '
      folder_separator_icon = '  '
      home_icon = ' '
      max_depth = 3.0
      style = 'agnoster_short'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#D6DEEB'
    template = '╰─'

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#D6DEEB'
    template = '❯ '

    [blocks.segments.properties]
      always_enabled = true

[transient_prompt]
  foreground = '#FEF5ED'
  background = 'transparent'
  template = ' '

[secondary_prompt]
  foreground = '#D6DEEB'
  background = 'transparent'
  template = '╰─❯ '
