#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    powerline_symbol = ''
    foreground = '#262b44'
    background = '#feae34'
    leading_diamond = ''
    trailing_diamond = ''
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#262b44'
    background = '#fee761'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#f77622{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#e43b44{{ end }}', '{{ if gt .Ahead 0 }}#2ce8f5{{ end }}', '{{ if gt .Behind 0 }}#f77622{{ end }}']
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#0095e9'
    background_templates = ['{{ if gt .Code 0 }}#ff0044{{ end }}']
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = '  '

    [blocks.segments.properties]
      always_enabled = true
