#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{if .Root}}⚡ {{end}}{{.Folder}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffce7b'
    template = '┌ '

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#1d1626'
    background = '#ffce7b'
    template = '   {{ if .SSHSession }}  {{ end }}{{ .UserName }}@{{ .HostName }} '

  [[blocks.segments]]
    type = 'os'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#fffef9'
    background = '#C678DD'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '

    [blocks.segments.properties]
      windows = ''

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#fffef9'
    background = '#C678DD'
    template = '{{ path .Path .Location }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#100e23'
    background = '#fffffb'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#fcaf17{{ end }}', '{{ if gt .Ahead 0 }}#95ffa4{{ end }}', '{{ if gt .Behind 0 }}#f7acbc{{ end }}', '{{ if .UpstreamGone }}#d1c7b7{{ end }}']
    template = ' {{ if( .UpstreamIcon ) }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <#ed1941> {{.Working.String}}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} <#225a1f> {{.Staging.String}}</>{{ end }}{{ if gt .StashCount 0 }}   {{.StashCount}}{{ end }}{{ if gt .WorktreeCount 0 }}{{if .IsWorkTree}}<#1d953f>{{ end }}   {{if .IsWorkTree}}</>{{ end }}{{.WorktreeCount}}{{ end }} '

    [blocks.segments.properties]
      azure_devops_icon = ' '
      bitbucket_icon = ' '
      branch_gone_icon = ' '
      branch_icon = ' '
      branch_identical_icon = ' '
      commit_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true
      git_icon = ' '
      github_icon = ' '
      gitlab_icon = ' '
      tag_icon = ' '

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#fffef9'
    background = '#33a3dc'
    template = '   {{ .FormattedMs }} '

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'status'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#fffef9'
    background = '#ed1941'
    template = '  >>{{ reason .Code }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffce7b'
    template = '└'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffffff'
    template = ' $'
