#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffffff'
    template = '<#C591E8>❯</><#69FF94>❯</>'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#56B6C2'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#D0666F'
    template = '<#5FAAE8>git:(</>{{ .HEAD }}<#5FAAE8>)</>'

    [blocks.segments.properties]
      branch_icon = ''
      fetch_status = false

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#DCB977'
    template = ' '

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#66F68F'
    template = ' {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04'
