#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = '#3A86FF'
    template = '{{ if .WSL }}WSL at {{ end }}{{.Icon}} '

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#f1184c'
    background = '#242424'
    template = ' {{ .UserName }}'

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#f1184c'
    background = '#242424'
    template = '- root '

  [[blocks.segments]]
    type = 'time'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#FFBB00'
    background = '#242424'
    template = '{{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '2006-01-02 15:04:05'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#33DD2D'
    background = '#242424'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#3A86FF'
    background = '#242424'
    template = '{{ .UpstreamIcon }}{{ .HEAD }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'status'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#242424'
    background = '#33DD2D'
    background_templates = ['{{ if gt .Code 0 }}#f1184c{{ end }}']
    template = '  '

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#f1184c'
    template = '➜ '
