#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{.UserName}}@{{.HostName}} : {{.Folder}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#0077c2'
    background = '#fbfbfb'
    leading_diamond = ''
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '

    [blocks.segments.properties]
      arch = ''
      debian = ''
      fedora = ''
      linux = ''
      macos = ''
      manjaro = ''
      opensuse = ''
      ubuntu = ''
      windows = ''

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#0077c2'
    background = '#fbfbfb'
    template = '{{ .UserName }}<#000000>@</><#e06c75>{{ .HostName }}</> '

    [blocks.segments.properties]
      display_host = true

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#e06c75'
    template = ' ⠀'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#0077c2'
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      folder_separator_icon = '/'
      home_icon = '~'
      max_depth = 2.0
      style = 'letter'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#193549'
    background = '#fffb38'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#f17c37{{ end }}', '{{ if gt .Behind 0 }}#89d1dc{{ end }}']
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#FFD54F'
    template = ' {{if .Root}}#{{else}}${{end}}'

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#ffffff'
    template = ' {{ if gt .Code 0 }}󰀰{{ else }}{{ end }} '

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#ffffff'
    template = '{{ .FormattedMs }} '

    [blocks.segments.properties]
      always_enabled = true

  [[blocks.segments]]
    type = 'battery'
    style = 'powerline'
    powerline_symbol = ''
    invert_powerline = true
    foreground = '#ffffff'
    background = '#f36943'
    background_templates = ['{{if eq "Charging" .State.String}}#40c4ff{{end}}', '{{if eq "Discharging" .State.String}}#ff5722{{end}}', '{{if eq "Full" .State.String}}#4caf50{{end}}']
    template = ' {{ if not .Error }}{{ .Icon }}{{ .Percentage }}{{ end }}{{ .Error }}% '

    [blocks.segments.properties]
      charged_icon = ' '
      charging_icon = ' '
      discharging_icon = ' '

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    invert_powerline = true
    foreground = '#ffffff'
    background = '#61afef'
    trailing_diamond = ''
    template = ' {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04 (Mon)'
