#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#88c0d0'
    template = '<#5e81ac>┏[</>{{ .UserName }}<#5e81ac>]</>'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#b48ead'
    template = '<#5e81ac>--[</>{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<#8fbcbb> ● </>{{ end }}{{ if .Staging.Changed }}<#88c0d0> ● </>{{ end }}<#5e81ac>]</>'

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'aws'
    style = 'plain'
    foreground = '#b48ead'
    template = '<#5e81ac>--[</>{{.Profile}}{{if .Region}}@{{.Region}}{{end}}<#5e81ac>]</>'

  [[blocks.segments]]
    type = 'kubectl'
    style = 'plain'
    foreground = '#b48ead'
    template = '<#5e81ac>--[</>{{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}<#5e81ac>]</>'

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#d8dee9'
    template = '<#5e81ac>[</><#5e81ac>]</>'

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#d8dee9'
    template = '<#5e81ac>[x</>{{ reason .Code }}<#5e81ac>]</>'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#88c0d0'
    template = '<#5e81ac>┖[</>{{ .Path }}<#5e81ac>]</>'

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#5e81ac'
    template = '  '
