#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
console_title_template = '{{ .UserName }}@{{ .HostName }}'
terminal_background = 'p:background'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = 'p:yellow'
    template = '{{ .UserName }}@{{ .HostName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'p:blue'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    template = '<p:yellow>git</>:({{ if or (.Working.Changed) (.Staging.Changed) (gt .StashCount 0) }}<p:magenta>{{ .HEAD }}</>{{ else }}<p:green>{{ .HEAD }}</>{{ end }}{{ if (gt .Ahead 0)}}<p:cyan>{{ .BranchStatus }}</>{{ end }}{{ if (gt .Behind 0)}}<p:cyan>{{ .BranchStatus }}</>{{ end }}{{ if .Staging.Changed }} <p:green>{{ .Staging.String }}</>{{ end }}{{ if .Working.Changed }} <p:red>{{ .Working.String }}</>{{ end }})'

    [blocks.segments.properties]
      branch_icon = ''
      fetch_stash_count = true
      fetch_status = true
      fetch_worktree_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = 'p:foreground'
    template = '{{ if gt .Code 0 }}<p:red>({{ .Code }}) </>{{ else }}<p:green>({{ .Code }}) </>{{ end }}> '

    [blocks.segments.properties]
      always_enabled = true

[palette]
  background = '#282c34'
  black = '#282c34'
  blue = '#61afef'
  cyan = '#56b6c2'
  foreground = '#dcdfe4'
  green = '#98c379'
  magenta = '#c678dd'
  red = '#e06c75'
  white = '#dcdfe4'
  yellow = '#e5c07b'
