#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffffff'
    template = '<#C591E8>❯</><#69FF94>❯</> '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#56B6C2'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#D0666F'
    template = '<#5FAAE8>git:(</>{{ .HEAD }}<#5FAAE8>)</>'

    [blocks.segments.properties]
      branch_icon = ''

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#DCB977'
    template = '  '

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'command'
    style = 'plain'
    foreground = '#ffffff'
    template = ' {{ .Output }} '

    [blocks.segments.properties]
      command = 'git log --pretty=format:%cr -1 || date +%H:%M:%S'
      shell = 'bash'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffffff'
    template = ' '
