#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    powerline_symbol = ''
    foreground = 'red'
    template = ' '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'blue'
    template = '{{ .Path }}'

    [blocks.segments.properties]
      folder_icon = ''
      folder_separator_icon = '/'
      home_icon = ''
      style = 'agnoster'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'green'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}', '{{ if gt .Ahead 0 }}red{{ end }}', '{{ if gt .Behind 0 }}green{{ end }}']
    template = ' on {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<red>  {{ .Working.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<yellow>  {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      github_icon = ' '

  [[blocks.segments]]
    type = 'dotnet'
    style = 'plain'
    foreground = 'magenta'
    template = ' [.NET] {{ if .Unsupported }}{{ else }}{{ .Full }}{{ end }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = 'yellow'
    template = '{{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04:05'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'green'
    template = '❯'
