#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{if .Root}}root :: {{end}}{{.Shell}} :: {{.Folder}}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'diamond'
    foreground = '#000000'
    background = '#ffea00'
    leading_diamond = '▓'

  [[blocks.segments]]
    type = 'kubectl'
    style = 'powerline'
    foreground = '#000000'
    background = '#ffea00'
    template = ' 󱃾 {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} '

  [[blocks.segments]]
    type = 'az'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#000000'
    background = '#008AD7'
    template = '  {{ .Name }} [ {{ .Origin }} ] '

    [blocks.segments.properties]
      source = 'cli'

  [[blocks.segments]]
    type = 'az'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#FFFFFF'
    background = '#012456'
    template = '  {{ .Name }} [ {{ .Origin }} ] '

    [blocks.segments.properties]
      source = 'pwsh'

  [[blocks.segments]]
    type = 'aws'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#000000'
    background = '#FFA400'
    template = ' 󰸏 {{.Profile}}{{if .Region}}@{{.Region}}{{end}}'

    [blocks.segments.properties]
      display_default = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#26C6DA'
    background = '#2f2f2f'
    leading_diamond = '▓'
    template = ' {{ if .WSL }}{{ .Icon }} on {{ end }} <#ffea00></>'

    [blocks.segments.properties]
      alpine = ''
      arch = ''
      centos = ''
      debian = ''
      elementary = ''
      fedora = ''
      gentoo = ''
      linux = ''
      macos = ''
      manjaro = ''
      mint = ''
      opensuse = ''
      raspbian = ''
      ubuntu = ''
      windows = ''

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    foreground = '#ffea00'
    background = '#2f2f2f'
    template = ' {{ if ne .Env.POSH_SESSION_DEFAULT_USER .UserName }}{{ .UserName }}{{ end }}<#ffea00> </>'

  [[blocks.segments]]
    type = 'root'
    style = 'diamond'
    foreground = '#ffea00'
    background = '#2f2f2f'
    template = ' <#ffea00> </>'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    foreground = '#fafafa'
    background = '#2f2f2f'
    template = '<#f2f200>  </>{{ .Path }} '

    [blocks.segments.properties]
      folder_icon = '<#B5B2C2> </>'
      folder_separator_icon = '<#ffea00> </>'
      home_icon = '  '
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'diamond'
    foreground = '#ffea00'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ffea00{{ end }}', '{{ if gt .Ahead 0 }}#2EC4B6{{ end }}', '{{ if gt .Behind 0 }}#8A4FFF{{ end }}']
    background = '#2f2f2f'
    template = '<#ffea00> </>{{ .UpstreamIcon }}{{ .HEAD }}{{ .BranchStatus }}{{ if .Working.Changed }}<#E84855>  {{ .Working.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#2FDA4E>  {{ .Staging.String }}</>{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'text'
    style = 'diamond'
    foreground = '#fafafa'
    background = '#2f2f2f'
    trailing_diamond = ''

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffea00'
    template = ' ❯ '
