#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'rprompt'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#00C5C7'
    template = ' {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#77E4F7'
    template = '{{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#FFE700'
    template = '{{ .HEAD }} '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#43D426'
    template = '❯ '
