#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#98C379'
    template = '➜'

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#56B6C2'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#D0666F'
    template = '<#5FAAE8>git:(</>{{ .HEAD }}<#5FAAE8>)</>'

    [blocks.segments.properties]
      branch_icon = ''

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#BF616A'
    template = ' ✗'
