#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#BF231D'
    background = '#E0E0E0'
    template = '  '

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = '#EF7D00'
    background = '#E0E0E0'
    template = ' {{ .Icon }} '

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#424242'
    background = '#E0E0E0'
    template = '{{ .UserName }}'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#424242'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#053F22{{ end }}', '{{ if or (gt .Ahead 0) (gt .Behind 0) }}#0A703E{{ end }}']
    background = '#E0E0E0'
    template = ' [{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}<#BD6200>  {{ .Working.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}<#053F22>  {{ .Staging.String }}</>{{ end }}] '

    [blocks.segments.properties]
      branch_max_length = 30.0
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#424242'
    background = '#E0E0E0'
    template = ' {{ .Path }}'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    powerline_symbol = ''
    foreground = '#424242'
    background = '#E0E0E0'
    template = '  {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }} '

    [blocks.segments.properties]
      text = ''

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#E0E0E0'
    template = ' '
