#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
console_title_template = '{{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hide'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    foreground = '#a9ffb4'
    template = ' {{ .FormattedMs }}s <#ffffff></>'

    [blocks.segments.properties]
      style = 'dallas'
      threshold = 0.0

  [[blocks.segments]]
    type = 'node'
    style = 'powerline'
    foreground = '#45bf17'
    template = '  {{ .Full }} '

  [[blocks.segments]]
    type = 'npm'
    style = 'powerline'
    foreground = '#FE4A49'
    template = '<#F3EFF5>and</>  {{ .Full }} '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true
  overflow = 'break'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    foreground = '#ffafd2'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      folder_icon = ''
      folder_separator_icon = ' ❯ '
      home_icon = 'home'
      style = 'agnoster_full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    foreground = '#f14e32'
    template = '({{ .HEAD }})'

    [blocks.segments.properties]
      branch_icon = ' '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    foreground = '#00c7fc'
    template = '<#00c7fc>❯</>_: '

    [blocks.segments.properties]
      always_enabled = true

[transient_prompt]
  foreground = '#FEF5ED'
  background = 'transparent'
  template = '{{ .Shell }}'
