#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#dd1e1e'
    background = '#000000'
    template = ' ⚡'

  [[blocks.segments]]
    type = 'os'
    style = 'plain'
    foreground = '#ffffff'
    background = '#000000'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}} '

    [blocks.segments.properties]
      alpine = ''
      arch = ''
      centos = ''
      debian = ''
      elementary = ''
      fedora = ''
      gentoo = ''
      linux = ''
      macos = ''
      manjaro = ''
      mint = ''
      opensuse = ''
      raspbian = ''
      ubuntu = ''
      windows = ''
      wsl = ''

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#43CCEA'
    background = '#4d4d4d'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      folder_icon = ''
      folder_separator_icon = '<transparent>  </>'
      home_icon = ''
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#00ff0d'
    background = '#4d4d4d'
    template = '<#000000> </>{{ .HEAD }}{{ if .Staging.Changed }}<#FF6F00>  {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#4d4d4d'
    trailing_diamond = ''
    template = '<#000000> </>{{ .FormattedMs }}s '

    [blocks.segments.properties]
      style = 'dallas'
      threshold = 0.0

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    foreground = '#43CCEA'
    background = '#4d4d4d'
    leading_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }}<transparent> / </>{{ .HostName }}'

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    foreground = '#43CCEA'
    background = '#4d4d4d'
    trailing_diamond = ''
    template = '<#000000>  </>{{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '3:04:05 PM'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#00ff0d'
    foreground_templates = ['{{ if gt .Code 0 }}#ff0000{{ end }}']
    template = ' '

    [blocks.segments.properties]
      always_enabled = true
