#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'shell'
    style = 'plain'
    foreground = '#007acc'
    template = '{{ .Name }}'

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#ff8080'
    template = ' <#757575,>as</> root'

  [[blocks.segments]]
    type = 'time'
    style = 'plain'
    foreground = '#689f38'
    template = ' <#757575,>|</> {{ .CurrentDate | date .Format }}'

    [blocks.segments.properties]
      time_format = '15:04:05'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#757575'
    template = '┌ {{ .UserName }}@{{ .HostName }} '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#100e23'
    background = '#91ddff'
    template = ' {{ .Path }} '

    [blocks.segments.properties]
      style = 'folder'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#100e23'
    background = '#95ffa4'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#c5b6ad{{ end }}']
    template = ' {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} │{{ end }}{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_ahead_icon = '↑'
      branch_behind_icon = '↓'
      branch_gone = '≢'
      branch_icon = ' '
      branch_identical_icon = '≡'
      cherry_pick_icon = '✓ '
      commit_icon = '▷ '
      fetch_stash_count = true
      fetch_status = true
      merge_icon = '◴ '
      no_commits_icon = '[no commits]'
      rebase_icon = 'Ɫ '
      tag_icon = '▶ '

  [[blocks.segments]]
    type = 'terraform'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#100e23'
    background = '#ffee58'
    template = ' {{ .WorkspaceName }} '

  [[blocks.segments]]
    type = 'status'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#ffffff'
    background = '#ff8080'
    template = ' error '

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#757575'
    template = '└ '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#ffffff'
    template = '$'
