#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    foreground = '#7eb8da'
    template = '┏[<#ffffff></> {{ .UserName }} from <#ffffff></> {{ .HostName }}]'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#be9ddf'
    template = '[<#ffffff></> {{ .FormattedMs }}s]'

    [blocks.segments.properties]
      style = 'dallas'
      threshold = 0.0

  [[blocks.segments]]
    type = 'root'
    style = 'diamond'
    template = ''

    [blocks.segments.properties]
      root_icon = ''

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'diamond'
    foreground = '#be9ddf'
    template = '[<#ffffff></> RAM: {{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB]'

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    foreground = '#7eb8da'
    template = '[<#ffffff></> {{ .CurrentDate | date .Format }}]'

    [blocks.segments.properties]
      time_format = 'Monday at 3:04:05 PM'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = '#ffa5d8'
    template = '[<#ffffff>{{ .UpstreamIcon }}</>{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} <#ffffff></> {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }} <#ffffff></> {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }} <#ffffff></> {{ .StashCount }}{{ end }}]'

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'aws'
    style = 'plain'
    foreground = '#ffa5d8'
    template = '[{{ .Profile }}{{if .Region}}@{{ .Region }}{{ end }}]'

  [[blocks.segments]]
    type = 'kubectl'
    style = 'plain'
    foreground = '#ffa5d8'
    template = '[{{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}}]'

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#ffa5d8'
    template = '[]'

  [[blocks.segments]]
    type = 'status'
    style = 'powerline'
    foreground = '#ffa5d8'
    template = '[<#ffffff></> Error, check your command]'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = '#7eb8da'
    template = '┖[<#98bfad>{{ .Path }}</>]'

    [blocks.segments.properties]
      style = 'full'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#7eb8da'
    template = '└─Δ'
