#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
console_title_template = '{{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    foreground = '#011627'
    background = '#FEF5ED'
    leading_diamond = ''
    trailing_diamond = '<transparent,#FEF5ED></>'
    template = ' {{ if .WSL }}WSL at {{ end }}{{.Icon}}'

    [blocks.segments.properties]
      macos = ' '
      ubuntu = ' '
      windows = ' '

  [[blocks.segments]]
    type = 'time'
    style = 'diamond'
    foreground = '#011627'
    background = '#FEF5ED'
    leading_diamond = ''
    trailing_diamond = '<transparent,#FEF5ED></>'
    template = ' ♥ {{ .CurrentDate | date .Format }} '

    [blocks.segments.properties]
      time_format = '15:04:05'

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#516BEB'
    leading_diamond = ''
    template = ' CPU: {{ round .PhysicalPercentUsed .Precision }}% | '

  [[blocks.segments]]
    type = 'sysinfo'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#516BEB'
    trailing_diamond = '<transparent,#516BEB></>'
    template = 'RAM: {{ (div ((sub .PhysicalTotalMemory .PhysicalFreeMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB  '

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#d6deeb'
    background = '#575656'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .FormattedMs }} '

    [blocks.segments.properties]
      style = 'roundrock'
      threshold = 0.0

[[blocks]]
  type = 'prompt'
  alignment = 'right'

  [[blocks.segments]]
    type = 'node'
    style = 'diamond'
    foreground = '#000000'
    background = '#ffffff'
    leading_diamond = ''
    trailing_diamond = '<transparent,#ffffff></>'
    template = ' {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}'

    [blocks.segments.properties]
      fetch_package_manager = true
      npm_icon = ' <#cc3a3a></> '
      yarn_icon = ' <#348cba></>'

  [[blocks.segments]]
    type = 'git'
    style = 'diamond'
    foreground = '#011627'
    background = '#17D7A0'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      branch_icon = ' '
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true
      fetch_worktree_count = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    foreground = '#ffafd2'
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      folder_icon = ''
      home_icon = 'home'
      style = 'agnoster_full'

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = '#00ff15'
    foreground_templates = ['{{ if gt .Code 0 }}#ff0000{{ end }}']
    template = '  '

    [blocks.segments.properties]
      always_enabled = true

[transient_prompt]
  foreground = '#FEF5ED'
  background = 'transparent'
  template = ' '
